[SPARK-36979][SQL][3.2] Add RewriteLateralSubquery rule into nonExcludableRules
### What changes were proposed in this pull request?

Add RewriteLateralSubquery rule into nonExcludableRules.

### Why are the changes needed?

Lateral Join has no meaning without rule `RewriteLateralSubquery`. So now if we set `spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.RewriteLateralSubquery`, the lateral join query will fail with:
```
java.lang.AssertionError: assertion failed: No plan for LateralJoin lateral-subquery#218
```

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

add test

Closes #34260 from ulysses-you/SPARK-36979-3-2.

Authored-by: ulysses-you <ulyssesyou18@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>