[SPARK-37859][SQL] Do not check for metadata during schema comparison
### What changes were proposed in this pull request?

Ignores the metadata when comparing the user-provided schema and the actual schema during BaseRelation resolution.

### Why are the changes needed?

Makes it possible to read tables with Spark 3.2 that were written with Spark 3.1, as https://github.com/apache/spark/blob/bd24b4884b804fc85a083f82b864823851d5980c/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala#L312 added a new metadata field that broke compatibility.

### Does this PR introduce _any_ user-facing change?

Yes. Previously, an error was thrown when a SQL table written with JDBC in Spark 3.1 was read in Spark 3.2. Now, no error is thrown.

### How was this patch tested?

Unit test and manual test with a SQL table written with Spark 3.1.

Query:

```
select * from jdbc_table
```

Before:

```
org.apache.spark.sql.AnalysisException: The user-specified schema doesn't match the actual schema:
```

After: no error

Closes #35158 from karenfeng/SPARK-37859.

Authored-by: Karen Feng <karen.feng@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit a1e86373253d77329b2b252c653a69ae8ac0bd6c)
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit 66e1231621fc0721a8b1a5e77a8ff84b8e665ea8)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>