[SPARK-38279][TESTS][3.2] Pin MarkupSafe to 2.0.1 fix linter failure
### What changes were proposed in this pull request?

This PR proposes to pin the Python package `markupsafe` to 2.0.1 to fix the CI failure as below.

```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/markupsafe/__init__.py)
```

Since `markupsafe==2.1.0` has removed `soft_unicode`, `from markupsafe import soft_unicode` no longer working properly.

See https://github.com/aws/aws-sam-cli/issues/3661 for more detail.

### Why are the changes needed?

To fix the CI failure on branch-3.2

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The existing tests are should be passed

Closes #35602 from itholic/SPARK-38279.

Authored-by: itholic <haejoon.lee@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>