[SPARK-36110][BUILD] Upgrade SBT to 1.5.5
### What changes were proposed in this pull request?

This PR upgrades SBT to `1.5.5`.

### Why are the changes needed?

SBT `1.5.5` was released, which includes 16 improvements/bug fixes.
https://github.com/sbt/sbt/releases/tag/v1.5.5

* Fixes remote caching not managing resource files
* Fixes launcher causing NoClassDefFoundError when launching sbt 1.4.0 - 1.4.2
* Fixes cross-Scala suffix conflict warning involving _3
* Fixes binaryScalaVersion of 3.0.1-SNAPSHOT
* Fixes carriage return in supershell progress state
* Fixes IntegrationTest configuration not tagged as test in BSP
* Fixes BSP task error handling
* Fixes handling of invalid range positions returned by Javac
* Fixes local class analysis
* Adds buildTarget/resources support for BSP
* Adds build.sbt support for BSP import
* Tracks source dependencies using OriginalTreeAttachments in Scala 2.13
* Reduces overhead in Analysis protobuf deserialization
* Minimizes unnecessary information in signature analysis
* Enables compile-to-jar for local Javac
* Enables Zinc cycle reporting when Scalac is not invoked

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI.

Closes #33312 from sarutak/upgrade-sbt-1.5.5.

Authored-by: Kousuke Saruta <sarutak@oss.nttdata.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit c46342e3d057bcc949b4caf016514ff05e0a1ebd)
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>